import Head from "next/head";
import "@component/styles/globals.css";
import "bootstrap/dist/css/bootstrap.css";
import Layout from "@component/components/layout/Layout";

export default function App({ Component, pageProps }) {
  return (
    <Layout>
      <Head>
        <title>Fitter Happier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </Layout>
  );
}
